### ISSUE TITLE
Could not compile `x11cap`

### ISSUE THREAD

**Issue by LuoZijun** [bryal/X11Cap#2]
Hi, What's wrong ?

My ENV:

System: OS X EL Capitan ( ver 10.11.4 with X server )
Rust    : rustc 1.8.0 (db2939409 2016-04-11)
Cargo : cargo 0.9.0-nightly (8fc3fd8 2016-02-29)

![image](https://cloud.githubusercontent.com/assets/717717/15113709/82cee1ba-1628-11e6-9519-50366831e341.png)

**Comment by bryal** [comment]
Sorry I have't responded!
You need to be on nightly to build this atm
